sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t henriquemazzoleni/Docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true henriquemazzoleni/Docker-react npm run test